// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'spectral-display': string;
  'spectralDisplay': string;
}
declare var cssExports: CssExports;
export = cssExports;
